name:                tuple-sop
version:             0.1.0.0
github:              "Ferdinand-vW/tuple-sop"
license:             GPL-3
author:              "Ferdinand van Walree"
maintainer:          "ferdinandvwalree@gmail.com"
copyright:           "2018 Ferdinand van Walree"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            functions on n-ary tuples using generics-sop
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Exports various functions on n-ary tuples. This library uses generics-sop
                     to create a generic representation of n-ary product types. To regain type inference, the exported functions
                     work only on tuples with at most 10 components.

dependencies:
- base >= 4.7 && < 5
- generics-sop

library:
  source-dirs: src
  exposed-modules: 
    - Data.Tuple.Ops

tests:
  tuple-sop-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tuple-sop
